### ISSUE TITLE
Tentei rodar o projeto, já usando Ionic 3 e deu este erro. Alguém sabe como solucionar?

### ISSUE THREAD

**Issue by akrs3** [sreesdas/oagt#1]
npm install --save @ionic-native/call-number@4.2.0
sqlApp@0.0.1 /Users/rairaoliveira/Documents/Estudos_Anne/FUNDAJ/TesteSqli
te/oagt-master
├── UNMET DEPENDENCY @angular/core@4.1.3
├── @ionic-native/call-number@4.2.0
└── UNMET DEPENDENCY rxjs@5.4.0

npm WARN @ionic-native/call-number@4.2.0 requires a peer of @angular/core
@* but none was installed.
npm WARN @ionic-native/call-number@4.2.0 requires a peer of rxjs@^5.0.1 b
ut none was installed.
npm WARN @ionic-native/core@3.12.1 requires a peer of rxjs@^5.0.1 but non
e was installed.

**Comment by sreesdas** [comment]
try this command : npm install --save @4.1.3
